package main

import (
	delivery "auth-service/internal/delivery/http"
	"auth-service/internal/migrations"
	"auth-service/internal/repository"
	"auth-service/internal/usecase"
	"auth-service/pkg/config"
	"auth-service/pkg/logger"
	"auth-service/pkg/metrics"
	"context"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	"github.com/prometheus/client_golang/prometheus/promhttp"

	_ "auth-service/docs" // generated by `swag init -g cmd/main.go`

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Helpdesk Auth Service API
// @version 1.0
// @description Authentication endpoints as clients see them: through the API Gateway (every path is prefixed with /auth).
// @description "Try it out" calls the gateway, so the origin of this page must be listed in the gateway ALLOWED_ORIGINS.
// @description Send the access token as `Bearer <token>` in the Authorization header.
// @host localhost:8080
// @BasePath /auth
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

func main() {
	_ = godotenv.Load() // ignore a missing .env in production (real environment variables are used)

	config.Load()

	port := config.AppConfig.AppPort
	jwtSecret := []byte(config.AppConfig.JWTSecret)

	logger.Init("auth-service")

	db, err := repository.NewPostgresDB()
	if err != nil {
		logger.Log.Fatal("failed to connect database:", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		logger.Log.Fatal("failed to get database instance:", err)
	}

	if err := migrations.Run(sqlDB, "users"); err != nil {
		logger.Log.Fatal("failed to run migrations:", err)
	}

	repo := repository.NewUserRepository(db)

	if err := bootstrapAdmin(repo); err != nil {
		logger.Log.Error("bootstrap admin: ", err)
	}

	usecase := usecase.NewAuthUsecase(repo)

	// refresh-token repository
	refreshRepo := repository.NewRefreshTokenRepository(db)

	// handler with its dependencies
	handler := delivery.NewAuthHandler(usecase, refreshRepo, jwtSecret, db, config.AppConfig.MaxSessionsPerUser)

	r := gin.Default()

	r.Use(metrics.GinMiddleware())
	r.GET("/metrics", gin.WrapH(promhttp.Handler()))

	// Swagger UI is only mounted when explicitly enabled (dev only): do not
	// expose the API schema publicly by default.
	if config.AppConfig.EnableSwagger {
		r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	// CORS is handled by the API Gateway (the only public entry point).
	// auth-service no longer serves browsers directly, so it does not need
	// its own CORS headers here.

	// Trace middleware
	r.Use(delivery.TraceMiddleware())

	// Shared across replicas via Redis when REDIS_URL is set; otherwise an
	// in-memory limiter, where N replicas would mean N x the limit.
	authLimiter := delivery.NewLimiter(config.AppConfig.RedisURL, "rl:auth:", config.AppConfig.AuthRateLimitRPS, config.AppConfig.AuthRateLimitBurst)
	delivery.RegisterRoutes(r, handler, config.AppConfig.InternalSecret, authLimiter)

	// Graceful shutdown
	srv := &http.Server{
		Addr:    ":" + port,
		Handler: r,
	}

	go func() {
		logger.Log.Info("auth-service running on port " + port)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Log.Fatal("listen: ", err)
		}
	}()

	// Wait for an interrupt signal (Ctrl+C or kill)
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	logger.Log.Info("Shutting down server...")

	// Give in-flight requests up to 5 seconds to finish
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		logger.Log.Fatal("Server forced to shutdown: ", err)
	}

	// Close the DB connection cleanly
	sqlDB.Close()
	logger.Log.Info("Server exiting")
}
